services:
  python:
    build:
      context: .
      dockerfile: Dockerfile.python
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./scripts:/app/scripts
      - ./data:/app/data
      - ./figures:/app/figures
    working_dir: /app
